from __future__ import annotations

from typing import Any

__all__ = [
    "CGroupLimits",
    "Component",
    "Cpu",
    "Disk",
    "DiskUsage",
    "ExitStatus",
    "Group",
    "IS_SUPPORTED_SYSTEM",
    "IpNetwork",
    "LoadAverage",
    "MINIMUM_CPU_UPDATE_INTERVAL",
    "MacAddress",
    "Motherboard",
    "Network",
    "Process",
    "Product",
    "SUPPORTED_SIGNALS",
    "System",
    "User",
    "__version__",
    "get_current_pid",
    "set_open_files_limit",
]

__version__: str
IS_SUPPORTED_SYSTEM: bool
MINIMUM_CPU_UPDATE_INTERVAL: float
SUPPORTED_SIGNALS: tuple[str, ...]

def get_current_pid() -> int: ...
def set_open_files_limit(limit: int) -> bool: ...

class MacAddress:
    @property
    def value(self) -> str: ...
    @property
    def is_unspecified(self) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class IpNetwork:
    @property
    def addr(self) -> str: ...
    @property
    def prefix(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class DiskUsage:
    @property
    def total_written_bytes(self) -> int: ...
    @property
    def written_bytes(self) -> int: ...
    @property
    def total_read_bytes(self) -> int: ...
    @property
    def read_bytes(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class Cpu:
    @property
    def cpu_usage(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def vendor_id(self) -> str: ...
    @property
    def brand(self) -> str: ...
    @property
    def frequency(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class Disk:
    @property
    def kind(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def file_system(self) -> str: ...
    @property
    def mount_point(self) -> str: ...
    @property
    def total_space(self) -> int: ...
    @property
    def available_space(self) -> int: ...
    @property
    def is_removable(self) -> bool: ...
    @property
    def is_read_only(self) -> bool: ...
    @property
    def usage(self) -> DiskUsage: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class Network:
    @property
    def interface(self) -> str: ...
    @property
    def received(self) -> int: ...
    @property
    def total_received(self) -> int: ...
    @property
    def transmitted(self) -> int: ...
    @property
    def total_transmitted(self) -> int: ...
    @property
    def packets_received(self) -> int: ...
    @property
    def total_packets_received(self) -> int: ...
    @property
    def packets_transmitted(self) -> int: ...
    @property
    def total_packets_transmitted(self) -> int: ...
    @property
    def errors_on_received(self) -> int: ...
    @property
    def total_errors_on_received(self) -> int: ...
    @property
    def errors_on_transmitted(self) -> int: ...
    @property
    def total_errors_on_transmitted(self) -> int: ...
    @property
    def mac_address(self) -> MacAddress: ...
    @property
    def ip_networks(self) -> tuple[IpNetwork, ...]: ...
    @property
    def mtu(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class Component:
    @property
    def temperature(self) -> float | None: ...
    @property
    def max(self) -> float | None: ...
    @property
    def critical(self) -> float | None: ...
    @property
    def label(self) -> str: ...
    @property
    def id(self) -> str | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class Group:
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class User:
    @property
    def id(self) -> str: ...
    @property
    def group_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def groups(self) -> tuple[Group, ...]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class CGroupLimits:
    @property
    def total_memory(self) -> int: ...
    @property
    def free_memory(self) -> int: ...
    @property
    def free_swap(self) -> int: ...
    @property
    def rss(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class Motherboard:
    @property
    def name(self) -> str | None: ...
    @property
    def vendor_name(self) -> str | None: ...
    @property
    def version(self) -> str | None: ...
    @property
    def serial_number(self) -> str | None: ...
    @property
    def asset_tag(self) -> str | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class Product:
    @property
    def name(self) -> str | None: ...
    @property
    def family(self) -> str | None: ...
    @property
    def serial_number(self) -> str | None: ...
    @property
    def stock_keeping_unit(self) -> str | None: ...
    @property
    def uuid(self) -> str | None: ...
    @property
    def version(self) -> str | None: ...
    @property
    def vendor_name(self) -> str | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class LoadAverage:
    @property
    def one(self) -> float: ...
    @property
    def five(self) -> float: ...
    @property
    def fifteen(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class ExitStatus:
    @property
    def code(self) -> int | None: ...
    @property
    def success(self) -> bool: ...
    @property
    def unix_signal(self) -> int | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class Process:
    @property
    def pid(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def cmd(self) -> list[str]: ...
    @property
    def exe(self) -> str | None: ...
    @property
    def environ(self) -> list[str]: ...
    @property
    def cwd(self) -> str | None: ...
    @property
    def root(self) -> str | None: ...
    @property
    def memory(self) -> int: ...
    @property
    def virtual_memory(self) -> int: ...
    @property
    def parent(self) -> int | None: ...
    @property
    def status(self) -> str: ...
    @property
    def start_time(self) -> int: ...
    @property
    def run_time(self) -> int: ...
    @property
    def cpu_usage(self) -> float: ...
    @property
    def accumulated_cpu_time(self) -> int: ...
    @property
    def disk_usage(self) -> DiskUsage: ...
    @property
    def user_id(self) -> str | None: ...
    @property
    def effective_user_id(self) -> str | None: ...
    @property
    def group_id(self) -> str | None: ...
    @property
    def effective_group_id(self) -> str | None: ...
    @property
    def session_id(self) -> int | None: ...
    @property
    def tasks(self) -> tuple[int, ...] | None: ...
    @property
    def thread_kind(self) -> str | None: ...
    @property
    def exists(self) -> bool: ...
    @property
    def open_files(self) -> int | None: ...
    @property
    def open_files_limit(self) -> int | None: ...
    def kill(self) -> bool: ...
    def kill_with(self, signal: str) -> bool | None: ...
    def kill_and_wait(self) -> ExitStatus | None: ...
    def kill_with_and_wait(self, signal: str) -> ExitStatus | None: ...
    def wait(self) -> ExitStatus | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class System:
    def __init__(self) -> None: ...
    @classmethod
    def new_empty(cls) -> System: ...
    @classmethod
    def new_with_specifics(
        cls,
        *,
        memory: bool = False,
        ram: bool = True,
        swap: bool = True,
        cpu: bool = False,
        cpu_usage: bool = True,
        cpu_frequency: bool = True,
        processes: bool = False,
        process_ids: list[int] | None = None,
        remove_dead_processes: bool = True,
        process_cpu: bool = False,
        process_disk_usage: bool = False,
        process_memory: bool = False,
        process_user: str = "never",
        process_cwd: str = "never",
        process_root: str = "never",
        process_environ: str = "never",
        process_cmd: str = "never",
        process_exe: str = "never",
        process_tasks: bool = True,
    ) -> System: ...
    @property
    def cpus(self) -> tuple[Cpu, ...]: ...
    @property
    def disks(self) -> tuple[Disk, ...]: ...
    @property
    def networks(self) -> tuple[Network, ...]: ...
    @property
    def components(self) -> tuple[Component, ...]: ...
    @property
    def users(self) -> tuple[User, ...]: ...
    @property
    def groups(self) -> tuple[Group, ...]: ...
    @property
    def processes(self) -> tuple[Process, ...]: ...
    @property
    def total_memory(self) -> int: ...
    @property
    def free_memory(self) -> int: ...
    @property
    def available_memory(self) -> int: ...
    @property
    def used_memory(self) -> int: ...
    @property
    def total_swap(self) -> int: ...
    @property
    def free_swap(self) -> int: ...
    @property
    def used_swap(self) -> int: ...
    @property
    def cgroup_limits(self) -> CGroupLimits | None: ...
    @property
    def uptime(self) -> int: ...
    @property
    def boot_time(self) -> int: ...
    @property
    def load_average(self) -> LoadAverage: ...
    @property
    def name(self) -> str | None: ...
    @property
    def kernel_version(self) -> str | None: ...
    @property
    def kernel_long_version(self) -> str: ...
    @property
    def os_version(self) -> str | None: ...
    @property
    def long_os_version(self) -> str | None: ...
    @property
    def distribution_id(self) -> str: ...
    @property
    def distribution_id_like(self) -> tuple[str, ...]: ...
    @property
    def host_name(self) -> str | None: ...
    @property
    def cpu_arch(self) -> str: ...
    @property
    def physical_core_count(self) -> int | None: ...
    @property
    def global_cpu_usage(self) -> float: ...
    @property
    def open_files_limit(self) -> int | None: ...
    @property
    def motherboard(self) -> Motherboard | None: ...
    @property
    def product(self) -> Product: ...
    @property
    def supported_signals(self) -> tuple[str, ...]: ...
    @property
    def is_supported_system(self) -> bool: ...
    @property
    def minimum_cpu_update_interval(self) -> float: ...
    def refresh_all(self) -> None: ...
    def refresh_memory(self) -> None: ...
    def refresh_memory_specifics(self, *, ram: bool = True, swap: bool = True) -> None: ...
    def refresh_cpu(self) -> None: ...
    def refresh_cpu_usage(self) -> None: ...
    def refresh_cpu_frequency(self) -> None: ...
    def refresh_cpu_all(self) -> None: ...
    def refresh_cpu_specifics(self, *, cpu_usage: bool = True, frequency: bool = True) -> None: ...
    def refresh_cpu_list(self, *, cpu_usage: bool = True, frequency: bool = True) -> None: ...
    def refresh_processes(
        self, pids: list[int] | None = None, remove_dead_processes: bool = True
    ) -> int: ...
    def refresh_processes_specifics(
        self,
        pids: list[int] | None = None,
        remove_dead_processes: bool = True,
        *,
        cpu: bool = False,
        disk_usage: bool = False,
        memory: bool = False,
        user: str = "never",
        cwd: str = "never",
        root: str = "never",
        environ: str = "never",
        cmd: str = "never",
        exe: str = "never",
        tasks: bool = True,
    ) -> int: ...
    def refresh_specifics(
        self,
        *,
        memory: bool = False,
        ram: bool = True,
        swap: bool = True,
        cpu: bool = False,
        cpu_usage: bool = True,
        cpu_frequency: bool = True,
        processes: bool = False,
        process_ids: list[int] | None = None,
        remove_dead_processes: bool = True,
        process_cpu: bool = False,
        process_disk_usage: bool = False,
        process_memory: bool = False,
        process_user: str = "never",
        process_cwd: str = "never",
        process_root: str = "never",
        process_environ: str = "never",
        process_cmd: str = "never",
        process_exe: str = "never",
        process_tasks: bool = True,
    ) -> int: ...
    def refresh_disks(self) -> None: ...
    def refresh_disks_specifics(
        self,
        remove_not_listed_disks: bool = True,
        *,
        kind: bool = True,
        storage: bool = True,
        io_usage: bool = True,
    ) -> None: ...
    def refresh_networks(self) -> None: ...
    def refresh_components(self) -> None: ...
    def refresh_users(self) -> None: ...
    def refresh_groups(self) -> None: ...
    def process(self, pid: int) -> Process | None: ...
    def processes_by_name(self, name: str) -> tuple[Process, ...]: ...
    def processes_by_exact_name(self, name: str) -> tuple[Process, ...]: ...
    def get_user_by_id(self, user_id: str) -> User | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
